---
title: "Calibrating toy cost-effectiveness models (updates)"
author: "Wael Mohammed"
date: "05/04/2022"
output:
  word_document: default
  html_document: default
---

## Progress report:
- Tried calibrating:
  1. A three state markov model:
    - All methods managed to predict the targets.
    - Adaptive MCMC MH failed to run due to singular values in the covariance matrix.
  2. A three state markov model with a micro-Sim version:
    - I had many issues running the optimisation algorithms. Most errors are due to a missing hessian matrix.
    - The optimisation algorithm suggested implausible value for some of the parameter.
  3. A hypothetical (dynamic) infections disease model:
    - A few issues with missing hessian matrices.
    - Implausible values for many of the parameters.
    - Introduced transformations to log and logit scales to overcome the unboundedness feature of the used optimisation algorithms.
    - Most optimisation algorithms proposed values that are significantly far from the target distribution.
    - Apparently, the transformation of input parameters introduced bias into the Bayesian calibration process. This is likely the reason why most Bayesian results were off the charts. 
    
    
    

